USE CarpeDiem
DECLARE @NAME Varchar (50)
SET @NAME = 'DAVID MARLOR'

SELECT MAX(CDUSERS.NAME) AS 'Name'
	, 'Carpe License' = 
		CASE
			WHEN CDUSERS.TIMEKEY = -1 THEN 'N'
			ELSE 'Y'
		END
	, 'Mobile License' =
		CASE
			WHEN CDUSERS.MOBILEKEY = -1 THEN 'N'
			ELSE 'Y'
		END
	, CDULINK.USERGRPID AS 'User Group Membership'
	, CDTLINK.TGROUPID AS 'Fee-Earner Group Membership'
	, CDU2TK.TKPRID AS 'Access to Users'
	, CDU2TKG.TGROUPID AS 'Access to Groups'
FROM CDUSERS AS CDUSERS
LEFT JOIN CDULINK AS CDULINK ON CDUSERS.USERID = CDULINK.USERID
LEFT JOIN CDU2TK AS CDU2TK ON CDUSERS.USERID = CDU2TK.USERID
LEFT JOIN CDU2TKG AS CDU2TKG ON CDUSERS.USERID = CDU2TKG.USERID
LEFT JOIN CDTLINK AS CDTLINK ON CDUSERS.TKPRID = CDTLINK.TKPRID
WHERE CDUSERS.NAME = @NAME
GROUP BY CDULINK.USERGRPID
	, CDU2TK.TKPRID
	, CDU2TKG.TGROUPID
	, CDTLINK.TGROUPID
	, CDUSERS.MOBILEKEY
	, CDUSERS.TIMEKEY
ORDER BY [User Group Membership]
	, [Fee-Earner Group Membership]
	, [Access to Users]
	, [Access to Groups]

